/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdCarousel: typeof import('./../../components/home/AdCarousel.vue')['default']
    AllIcon: typeof import('./../../components/AnimatedIcons/AllIcon.vue')['default']
    BackGround: typeof import('./../../components/home/BackGround.vue')['default']
    BigWinsCarousel: typeof import('./../../components/home/BigWinsCarousel.vue')['default']
    ChatIcon: typeof import('./../../components/AnimatedIcons/ChatIcon.vue')['default']
    copy: typeof import('./../../components/layout/TopBar copy.vue')['default']
    DesktopSection: typeof import('./../../components/layout/DesktopSection.vue')['default']
    FilterBar: typeof import('./../../components/home/FilterBar.vue')['default']
    FishIcon: typeof import('./../../components/AnimatedIcons/FishIcon.vue')['default']
    FlameEffectOverlay: typeof import('./../../components/home/FlameEffectOverlay.vue')['default']
    FooterBar: typeof import('./../../components/layout/FooterBar.vue')['default']
    FooterBarMobile: typeof import('./../../components/layout/FooterBarMobile.vue')['default']
    GameCarousel: typeof import('./../../components/home/GameCarousel.vue')['default']
    GlobalLoading: typeof import('./../../components/common/GlobalLoading.vue')['default']
    GoogleOneTap: typeof import('./../../components/GoogleOneTap.vue')['default']
    LayoutAuthenticated: typeof import('./../../components/layout/LayoutAuthenticated.vue')['default']
    Logo: typeof import('./../../components/common/Logo.vue')['default']
    MobileSection: typeof import('./../../components/layout/MobileSection.vue')['default']
    PlayerAvatar: typeof import('./../../components/layout/PlayerAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowToasts: typeof import('./../../components/common/ShowToasts.vue')['default']
    SlotsIcon: typeof import('./../../components/AnimatedIcons/SlotsIcon.vue')['default']
    TopBar: typeof import('./../../components/layout/TopBar.vue')['default']
    TopBarMobile: typeof import('./../../components/layout/TopBarMobile.vue')['default']
    VGSprite: typeof import('./../../components/common/VGSprite.vue')['default']
    VSprite: typeof import('./../../components/common/VSprite.vue')['default']
    WheelIcon: typeof import('./../../components/AnimatedIcons/WheelIcon.vue')['default']
    XPStars: typeof import('./../../components/animation/XPStars.vue')['default']
  }
}
