/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BigWinsCarousel: typeof import('./../../components/home/BigWinsCarousel.vue')['default']
    copy: typeof import('./../../components/common/Logo copy.vue')['default']
    DesktopSection: typeof import('./../../components/common/DesktopSection.vue')['default']
    FilterBar: typeof import('./../../components/home/FilterBar.vue')['default']
    GameCarousel: typeof import('./../../components/home/GameCarousel.vue')['default']
    GlobalLoading: typeof import('./../../components/common/GlobalLoading.vue')['default']
    GoogleOneTap: typeof import('./../../components/GoogleOneTap.vue')['default']
    LayoutAuthenticated: typeof import('./../../components/layout/LayoutAuthenticated.vue')['default']
    Logo: typeof import('./../../components/common/Logo.vue')['default']
    MobileSection: typeof import('./../../components/common/MobileSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowToasts: typeof import('./../../components/common/ShowToasts.vue')['default']
    XPStars: typeof import('./../../components/animation/XPStars.vue')['default']
  }
}
