// This file was auto-generated by prisma-generator-typescript-interfaces

export type ChatChannel = "LOBBY" | "GAME" | "TOURNAMENT" | "PRIVATE";

export type FriendshipStatus = "PENDING" | "ACCEPTED" | "BLOCKED";

export type Gender = "BOY" | "GIRL" | "ALIEN" | "UNSURE" | "ROBOT" | "COMPLICATED";

export type NotificationType = "SYSTEM" | "FRIEND_REQUEST" | "ACHIEVEMENT" | "BALANCE_UPDATE" | "PROMOTIONAL" | "TOURNAMENT";

export type TransactionStatus = "PENDING" | "COMPLETED" | "FAILED" | "CANCELLED" | "REFUNDED" | "EXPIRED" | "REJECTED";

export type TransactionType = "DEPOSIT" | "WITHDRAWAL" | "BET" | "WIN" | "BONUS" | "DONATION" | "ADJUSTMENT" | "TOURNAMENT_BUYIN" | "TOURNAMENT_PRIZE";

export type UserStatus = "ACTIVE" | "INACTIVE" | "ONLINE" | "OFFLINE";

export type GameCategory = "TABLE" | "FISH" | "POKER" | "SLOTS" | "OTHER";

export type key_mode = "read" | "write" | "all" | "upload";

export type message_state = "read" | "unread" | "group";

export type platform_os = "ios" | "android";

export type product_cost = "D500" | "D1000" | "D2000" | "D5000" | "D10000";

export type request_status = "PENDING" | "SUCCESS" | "ERROR";

export type stripe_status = "created" | "succeeded" | "updated" | "failed" | "deleted" | "canceled";

export type transaction_status = "PENDING" | "COMPLETED" | "DENIED";

export type usage_mode = "last_saved" | "min5" | "day" | "cycle";

export type user_min_right = "read" | "upload" | "write" | "admin";

export type user_role = "read" | "upload" | "write" | "admin";

export type user_status = "ONLINE" | "OFFLINE" | "BUSY" | "AWAY";

export type volatility = "HIGH" | "MEDIUM" | "LOW";

export type RainType = "GAME" | "CHAT" | "MANUAL";

export type MemberRole = "ADMIN" | "MEMBER" | "GUEST" | "USER";

export type InvitationStatus = "PENDING" | "ACCEPTED" | "REJECTED";

export interface Achievement {
  id: string;
  name: string;
  description: string;
  targetXp: number;
  reward: number | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date | null;
  userachievement: Userachievement[];
}

export interface User {
  id: string;
  sbId: string | null;
  username: string | null;
  displayUsername: string | null;
  name: string;
  email: string;
  emailVerified: boolean | null;
  isOnline: boolean | null;
  isAnonymous: boolean | null;
  image: string | null;
  createdAt: Date;
  updatedAt: Date | null;
  twoFactorEnabled: boolean | null;
  role: MemberRole | null;
  banned: boolean | null;
  banReason: string | null;
  banExpires: Date | null;
  passwordHash: string | null;
  totalXp: number;
  balance: number;
  isVerified: boolean;
  active: boolean;
  lastLogin: Date | null;
  verificationToken: string | null;
  avatar: string | null;
  activeProfileId: string | null;
  gender: Gender | null;
  status: UserStatus | null;
  cashtag: string | null;
  phpId: number | null;
  accessToken: string | null;
  vipInfoId: string | null;
  lastDailySpin: Date | null;
  operator: Operator[];
  activeProfile: Profile[];
  RainBet: RainBet[];
  RainHistory: RainHistory[];
  RainTip: RainTip[];
  RainWinner: RainWinner[];
  sessions: Session[];
  accounts: Account[];
  chatmessage: Chatmessage[];
  friendshipFriendshipFriendidtouser: Friendship[];
  friendshipFriendshipUseridtouser: Friendship[];
  invitations: Invitation[];
  members: Member[];
  notification: Notification[];
  tournamententry: Tournamententry[];
  twofactors: TwoFactor[];
  userachievement: Userachievement[];
  vipInfo: VipInfo | null;
}

export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date | null;
  user: User;
}

export interface Session {
  id: string;
  userId: string;
  activeGameId: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  expiresAt: Date;
  createdAt: Date;
  refreshToken: string | null;
  active: boolean;
  token: string;
  updatedAt: Date | null;
  user: User;
}

export interface Operator {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  description: string | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date | null;
  acceptedPayments: string[];
  ownerId: string;
  balance: number;
  owner: User;
  profiles: Profile[];
  games: Game[];
  products: Product[];
  tournaments: Tournament[];
  VipInfo: VipInfo[];
}

export interface Message {
  id: string;
  content: string | null;
  createdAt: Date;
  updatedAt: Date | null;
  authorId: string | null;
}

export interface Profile {
  id: string;
  balance: number;
  xpEarned: number;
  isActive: boolean;
  lastPlayed: Date | null;
  createdAt: Date;
  updatedAt: Date | null;
  phpId: number | null;
  userId: string;
  currency: string;
  shopId: string;
  operator: Operator;
  userProfileUseridtouser: User;
  gamesession: GameSession[];
  tournamententry: Tournamententry[];
  transactions: Transaction[];
}

export interface Game {
  id: string;
  name: string;
  title: string;
  temperature: string | null;
  developer: string | null;
  vipLevel: number | null;
  isActive: boolean | null;
  device: number | null;
  featured: boolean | null;
  gamebank: string | null;
  bet: number | null;
  denomination: number | null;
  categoryTemp: number | null;
  originalId: number | null;
  bids: number | null;
  statIn: number | null;
  statOut: number | null;
  currentRtp: number | null;
  rtpStatIn: number | null;
  rtpStatOut: number | null;
  standardRtp: number | null;
  popularity: number | null;
  chanceFirepot1: number | null;
  chanceFirepot2: number | null;
  chanceFirepot3: number | null;
  fireCount1: number | null;
  fireCount2: number | null;
  fireCount3: number | null;
  linesPercentConfigSpin: string | null;
  linesPercentConfigSpinBonus: string | null;
  linesPercentConfigBonus: string | null;
  linesPercentConfigBonusBonus: string | null;
  rezerv: number | null;
  cask: number | null;
  advanced: string | null;
  scaleMode: string;
  slotViewState: string;
  view: number | null;
  categoryId: string | null;
  operatorId: string | null;
  providerId: string | null;
  createdAt: Date;
  updatedAt: Date | null;
  jackpotGroupId: string | null;
  active: boolean;
  password: string | null;
  category: GameCategory;
  operator: Operator | null;
  gamesession: GameSession[];
  tournamentgame: Tournamentgame[];
}

export interface Operatorgame {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  thumbnail: string | null;
  minBet: number | null;
  maxBet: number | null;
  xpMultiplier: number;
  isActive: boolean;
  isPromoted: boolean;
  createdAt: Date;
  updatedAt: Date | null;
  operatorId: string;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface Organization {
  id: string;
  name: string;
  slug: string | null;
  logo: string | null;
  createdAt: Date;
  metadata: string | null;
  invitations: Invitation[];
  members: Member[];
}

export interface Member {
  id: string;
  organizationId: string;
  userId: string;
  role: string;
  createdAt: Date;
  organization: Organization;
  user: User;
}

export interface Invitation {
  id: string;
  organizationId: string;
  email: string;
  role: string | null;
  expiresAt: Date;
  status: InvitationStatus;
  inviterId: string;
  user: User;
  organization: Organization;
}

export interface TwoFactor {
  id: string;
  secret: string;
  backupCodes: string;
  userId: string;
  user: User;
}

export interface Chatmessage {
  id: string;
  content: string;
  channel: ChatChannel;
  metadata: JsonValue | null;
  createdAt: Date;
  userId: string;
  roomId: string | null;
  chatroom: ChatRoom | null;
  user: User;
}

export interface ChatRoom {
  id: string;
  name: string;
  isGameRoom: boolean;
  createdAt: Date;
  gameSessionId: string | null;
  chatmessage: Chatmessage[];
  gamesession: GameSession | null;
}

export interface Friendship {
  id: string;
  status: FriendshipStatus;
  createdAt: Date;
  updatedAt: Date | null;
  userId: string;
  friendId: string;
  userFriendshipFriendidtouser: User;
  userFriendshipUseridtouser: User;
}

export interface GameSession {
  id: string;
  startTime: Date;
  endTime: Date | null;
  betAmount: number | null;
  winAmount: number | null;
  xpEarned: number;
  metadata: JsonValue | null;
  gameId: string;
  tournamentId: string | null;
  active: boolean;
  profileId: string;
  chatRoom: ChatRoom[];
  game: Game;
  profile: Profile;
  tournament: Tournament | null;
  Transaction: Transaction[];
  VipInfo: VipInfo | null;
  vipInfoId: string | null;
}

export interface Product {
  id: string;
  title: string;
  description: string;
  url: string;
  productType: string;
  bonusCode: string | null;
  bonusTotalInCredits: number;
  priceInCents: number;
  amountToReceiveInCredits: number;
  bestValue: number;
  discountInCents: number;
  bonusSpins: number;
  isPromo: boolean | null;
  totalDiscountInCents: number;
  shopId: string | null;
  createdAt: Date;
  updatedAt: Date | null;
  operator: Operator | null;
  transactions: Transaction[];
}

export interface Notification {
  id: string;
  notficationType: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  readAt: Date | null;
  metadata: JsonValue | null;
  createdAt: Date;
  userId: string;
  user: User;
}

export interface Tournament {
  id: string;
  name: string;
  description: string | null;
  startTime: Date;
  endTime: Date;
  entryFee: number | null;
  prizePool: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date | null;
  operatorId: string;
  leaderboard: JsonValue | null;
  gamesession: GameSession[];
  operator: Operator;
  tournamententry: Tournamententry[];
  tournamentgame: Tournamentgame[];
}

export interface Tournamententry {
  id: string;
  score: number;
  wagered: number;
  won: number;
  joinedAt: Date;
  userId: string;
  tournamentId: string;
  profileId: string;
  profile: Profile;
  tournament: Tournament;
  user: User;
}

export interface Tournamentgame {
  id: string;
  multiplier: number;
  tournamentId: string;
  gameId: string;
  game: Game;
  tournament: Tournament;
}

export interface Transaction {
  id: string;
  transactionType: TransactionType;
  amount: number;
  amountCredits: number;
  buyerCashtag: string | null;
  buyerUserId: string | null;
  username: string | null;
  cashiername: string | null;
  cashierAvatar: string | null;
  cashierId: string | null;
  reference: string | null;
  status: TransactionStatus;
  metadata: JsonValue | null;
  isRealMoney: boolean;
  paymentMethod: string | null;
  paymentDetails: JsonValue | null;
  createdAt: Date;
  processedAt: Date | null;
  gameSessionId: string | null;
  profileId: string | null;
  cashtag: string | null;
  gamesession: GameSession | null;
  profile: Profile | null;
  product: Product | null;
  productid: string | null;
  vipInfo: VipInfo | null;
  vipInfoId: string | null;
}

export interface Userachievement {
  id: string;
  progress: number;
  isUnlocked: boolean;
  unlockedAt: Date | null;
  createdAt: Date;
  updatedAt: Date | null;
  userId: string;
  achievementId: string;
  achievement: Achievement;
  user: User;
}

export interface RainBet {
  id: string;
  rainHistoryId: string;
  userId: string;
  betAmount: number;
  odds: number;
  outcome: string | null;
  settledAt: Date | null;
  RainHistory: RainHistory;
  user: User;
}

export interface RainHistory {
  id: string;
  userId: string;
  amount: number;
  rainType: RainType;
  createdAt: Date;
  RainBet: RainBet[];
  user: User;
  RainTip: RainTip[];
  RainWinner: RainWinner[];
}

export interface RainTip {
  id: string;
  rainHistoryId: string;
  userId: string;
  tipAmount: number;
  tippedAt: Date;
  RainHistory: RainHistory;
  user: User;
}

export interface RainWinner {
  id: string;
  rainHistoryId: string;
  userId: string;
  wonAmount: number;
  wonAt: Date;
  RainHistory: RainHistory;
  user: User;
}

export interface VipInfo {
  id: string;
  level: number;
  deposit_exp: number;
  bet_exp: number;
  rank_bet_exp: number;
  rank_deposit_exp: number;
  rank_name: string | null;
  icon: string | null;
  exp_switch_type: number | null;
  now_deposit_exp: string | null;
  level_deposit_exp: string | null;
  now_bet_exp: string | null;
  level_bet_exp: string | null;
  telegram: string | null;
  is_protection: boolean;
  protection_deposit_exp: string | null;
  protection_deposit_amount: string | null;
  protection_bet_exp: string | null;
  protection_bet_amount: string | null;
  protection_days: number | null;
  protection_switch: number | null;
  cycle_award_switch: boolean;
  level_award_switch: boolean;
  signin_award_switch: boolean;
  bet_award_switch: boolean;
  withdrawal_award_switch: boolean;
  unprotection_deposit_exp: string | null;
  unprotection_deposit_amount: string | null;
  unprotection_bet_exp: string | null;
  unprotection_bet_amount: string | null;
  unprotection_days: number | null;
  unprotection_switch: number | null;
  main_currency: string | null;
  can_receive_level_award: boolean;
  can_receive_rank_award: boolean;
  can_receive_day_award: boolean;
  can_receive_week_award: boolean;
  can_receive_month_award: boolean;
  can_receive_signin_award: boolean;
  can_receive_bet_award: boolean;
  can_receive_withdrawal_award: boolean;
  userid: string | null;
  free_spin_times: number | null;
  week_gift: number | null;
  month_gift: number | null;
  upgrade_gift: number | null;
  now_cash_back: number | null;
  yesterday_cash_back: number | null;
  history_cash_back: number | null;
  gamesession: GameSession[];
  operator: Operator | null;
  transactions: Transaction[];
  user: User | null;
  operatorId: string | null;
}

export interface EventLog {
  id: bigint;
  tableName: string;
  rowId: string | null;
  operation: string;
  payload: JsonValue | null;
  createdAt: Date | null;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
